version: "3.9"
services:
  backend:
    build: ./backend
    image: gergelykisshun/bug-tracker-backend
    container_name: backend_c
    ports: 
      - "3001:3001"
    volumes:
      - ./backend:/app
      - ./app/node_modules
  frontend:
    build: ./frontend
    image: gergelykisshun/bug-tracker-frontend
    container_name: frontend_c
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
